#ifndef __PACKET_H__
#define __PACKET_H__

#define PACKET_TYPE_CONN_REQ 1
#define PACKET_TYPE_CONN_ACK 2
#define PACKET_TYPE_PING_REQ 3
#define PACKET_TYPE_PING_ACK 4
#define PACKET_TYPE_STR_REQ 5
#define PACKET_TYPE_STR_ACK 6
#define PACKET_TYPE_EXIT_REQ 7
#define PACKET_TYPE_EXIT_ACK 8
#define PACKET_TYPE_LETTERING_ADD_REQ 9
#define PACKET_TYPE_LETTERING_ADD_ACK 10
#define PACKET_TYPE_LETTERING_DEL_REQ 11
#define PACKET_TYPE_LETTERING_DEL_ACK 12
#define PACKET_TYPE_REJECT_CALL_ADD_REQ 13
#define PACKET_TYPE_REJECT_CALL_ADD_ACK 14
#define PACKET_TYPE_REJECT_CALL_DEL_REQ 15
#define PACKET_TYPE_REJECT_CALL_DEL_ACK 16
#define PACKET_TYPE_CALL_FORWARDING_ADD_REQ 17
#define PACKET_TYPE_CALL_FORWARDING_ADD_ACK 18
#define PACKET_TYPE_CALL_FORWARDING_DEL_REQ 19
#define PACKET_TYPE_CALL_FORWARDING_DEL_ACK 20
#define PACKET_TYPE_SIGN_UP_REQ 21
#define PACKET_TYPE_SIGN_UP_ACK 22
#define PACKET_TYPE_CREATE_CHATROOM_REQ 23
#define PAKCET_TYPE_CREATE_CHATROOM_ACK 24
#define PACKET_TYPE_INVITE_REQ 25
#define PACKET_TYPE_INVITE_ACK 26
#define PACKET_TYPE_EXIT_CHATROOM_REQ 27
#define PACKET_TYPE_EXIT_CHATROOM_ACK 28
#define PACKET_TYPE_ALRAM_REQ 29
#define PACKET_TYPE_ALRAM_ACK 30
#define PACKET_TYPE_ALL_USER_REQ 31
#define PACKET_TYPE_ALL_USER_ACK 32

#define PACKET_STRING_MAX 1024

typedef struct PacketBody
{
    char str[1024];
} packetBody_t;

typedef struct PacketHead
{
    int type;
    char srcName[20];
    char dstName[20];
    long time;
    int bodyLength;
} packetHead_t;

#endif
